### ISSUE TITLE
Schema - Add graphic_overview field

### ISSUE THREAD

**Issue by mjanez** [mjanez/ckanext-scheming_dcat#3]
### Context info
> Description: 
> Graphic that provides an illustration of the dataset

- Pygeometa [MCF Core schema](https://github.com/geopython/pygeometa/blob/835a41f24464d0011e4825407a502bf4a43bcb96/pygeometa/schemas/mcf/core.yaml#L216-L218)

- XML Schema ISO19139 `gmd:graphicOverview`:

  ```xml
  <gmd:identificationInfo>
  ...
    <gmd:graphicOverview>
      <gmd:MD_BrowseGraphic>
        <gmd:fileName>
          <gco:CharacterString>{{ record['identification']['browsegraphic']|e }}</gco:CharacterString>
          </gmd:fileName>
      </gmd:MD_BrowseGraphic>
    </gmd:graphicOverview>
  </gmd:identificationInfo>
  ```

#### Basic
- [x] Add element to schemas.
```yaml
- field_name: graphic_overview
  label:
    en: Graphic overview of the dataset
    es: Descripción gráfica del conjunto de datos
  display_snippet: link_name.html
  form_placeholder: http://example.com/dataset.jpg
  help_text:
    en: "Graphic that provides an illustration of the dataset."
    es: "Gráfico que ilustra el conjunto de datos."
```

- [x] Add element to [ckan-pycsw ckan GeoDCAT-AP schema](https://github.com/mjanez/ckan-pycsw/blob/8c2c462526fa3e4f290da25be4d03121a1191407/ckan2pycsw/schemas/ckan/iso19139_geodcatap/main.j2#L72)
- [x] Update [ckan-pycsw pygeometa INSPIRE ISO19139 schema](https://github.com/mjanez/ckan-pycsw/blob/8c2c462526fa3e4f290da25be4d03121a1191407/ckan2pycsw/schemas/pygeometa/iso19139_inspire/main.j2#L182)

#### Enhancements
- [ ] Add a custom snippet to upload image from web or use [`/form_snippet/upload.html`](https://github.com/mjanez/ckanext-scheming/blob/master/ckanext/scheming/templates/scheming/form_snippets/upload.html)
